"""Properties for ``text_to_json_cmd`` and the supporting swar strategy.

T5A established the genesis property — a single composite assertion that
every (text, expected_json) pair from ``strategies.debug_command`` round-
trips through the parser. T5B expands coverage with shape-specific
properties so a regression in one arm shows up with a precise failure
rather than as a needle in the composite haystack.

Properties added in T5B:

- ``test_prop_swar_dict_has_required_fields`` — every ``swar`` dict
  generated by the strategy carries the three structural keys.
- ``test_prop_achal_rule`` — Sa and Pa are never tagged Komal or Tivra.
- ``test_prop_nullary_envelope_shape`` — every nullary text command
  parses to ``{<Variant>: {}}`` (single key, empty payload).
- ``test_prop_set_debug_all_tokens_canonical`` — every ``set-debug`` text
  token (on/off/true/false/1/0) parses to the canonical ``SetDebug``
  shape with the expected boolean.
- ``test_prop_subdivision_round_trip`` — ``subdivision N`` /
  ``set-subdivision N`` produce ``{"SetSubdivision": {"n": N}}`` for any
  positive integer.
- ``test_prop_swar_group_splits_chars`` — ``group <chars>`` and
  ``swar-group <chars>`` split the chars string into a per-character list.
- ``test_prop_focus_aliases_equivalent`` — both ``focus`` and
  ``focus-editor`` parse to the same ``{"FocusEditor": {}}`` envelope.
- ``test_prop_press_preserves_key`` — ``press <KEY>`` echoes the key
  verbatim under ``{"Press": {"key": ...}}``.
- ``test_prop_unknown_command_raises`` — any text whose head is not a
  known command name raises ``ValueError`` rather than silently producing
  a wrong-shaped dict.

We deliberately keep ``max_examples`` at Hypothesis's default (100) and
narrow each strategy enough that the suite stays under a second.
"""
from __future__ import annotations

from typing import Any

import pytest
from hypothesis import given

from transport_ws import text_to_json_cmd

from .strategies import (
    NOTES,
    OCTAVES,
    VARIANTS,
    debug_command,
    focus_command,
    nullary_command,
    press_command,
    set_debug_command,
    subdivision_command,
    swar,
    swar_group_command,
    type_command,
    unknown_command_text,
)


# ─── T5A: composite round-trip (kept) ──────────────────────────────────────


@given(debug_command())
def test_prop_text_parses_to_canonical_json(pair: tuple[str, dict[str, Any]]) -> None:
    """Every (text, expected_json) pair drawn from ``debug_command`` must
    round-trip through ``text_to_json_cmd`` to its declared shape.

    Asserts:
      - The parser does not raise for canonical inputs.
      - The returned dict equals the canonical JSON encoding.
    """
    text, expected = pair
    assert text_to_json_cmd(text) == expected


# ─── T5B: swar strategy shape properties ───────────────────────────────────


@given(swar())
def test_prop_swar_dict_has_required_fields(s: dict[str, str]) -> None:
    """Every generated swar carries the three structural keys used by
    sangeet-core's ``Swar`` codec — note, variant, octave — with values
    drawn from the canonical enumerations.
    """
    assert set(s.keys()) == {"note", "variant", "octave"}
    assert s["note"] in NOTES
    assert s["variant"] in VARIANTS
    assert s["octave"] in OCTAVES


@given(swar())
def test_prop_achal_rule(s: dict[str, str]) -> None:
    """Sa and Pa are achal — they only ever take the Shuddha variant.

    This is the cardinal Hindustani-music invariant baked into the swar
    strategy. If a future refactor lets Komal-Sa or Tivra-Pa leak through
    the generator, this property catches it immediately rather than
    surfacing as a confusing failure in a downstream test.
    """
    if s["note"] in ("Sa", "Pa"):
        assert s["variant"] == "Shuddha", (
            f"achal rule violated: {s['note']} got variant {s['variant']}"
        )


# ─── T5B: per-arm parser shape properties ──────────────────────────────────


@given(nullary_command())
def test_prop_nullary_envelope_shape(pair: tuple[str, dict[str, Any]]) -> None:
    """Every nullary command parses to a single-key dict with ``{}`` value.

    This is the circe-encoded shape for parameterless ADT variants — a
    regression where the parser starts emitting ``null`` or omitting the
    empty object payload would break the Elm bridge's decoder.
    """
    text, _ = pair
    result = text_to_json_cmd(text)
    assert isinstance(result, dict)
    assert len(result) == 1
    (variant_name, payload), = result.items()
    assert payload == {}, f"nullary {variant_name!r} produced non-empty payload {payload!r}"


@given(set_debug_command())
def test_prop_set_debug_all_tokens_canonical(
    pair: tuple[str, dict[str, Any]],
) -> None:
    """Every accepted ``set-debug`` token parses to the canonical shape.

    Covers all six boolean aliases (on/true/1, off/false/0). The parser
    must produce ``{"SetDebug": {"enabled": <bool>}}`` regardless of which
    alias was used.
    """
    text, expected = pair
    result = text_to_json_cmd(text)
    assert result == expected
    assert "SetDebug" in result
    assert isinstance(result["SetDebug"]["enabled"], bool)


@given(subdivision_command())
def test_prop_subdivision_round_trip(pair: tuple[str, dict[str, Any]]) -> None:
    """``subdivision N`` / ``set-subdivision N`` round-trip the integer.

    Asserts the parser keeps ``n`` as a Python int (not a string) and the
    envelope key is exactly ``SetSubdivision``.
    """
    text, expected = pair
    result = text_to_json_cmd(text)
    assert result == expected
    assert isinstance(result["SetSubdivision"]["n"], int)
    assert result["SetSubdivision"]["n"] >= 1


@given(swar_group_command())
def test_prop_swar_group_splits_chars(pair: tuple[str, dict[str, Any]]) -> None:
    """``group <chars>`` splits the chars string into a per-character list.

    A regression where the parser stops splitting (e.g. keeps ``"srg"`` as
    a single string) would break the bridge's expected ``List[String]``.
    """
    text, expected = pair
    result = text_to_json_cmd(text)
    assert result == expected
    notes = result["SwarGroup"]["notes"]
    assert isinstance(notes, list)
    # Each entry must be exactly one char — the parser splits per-character.
    assert all(isinstance(n, str) and len(n) == 1 for n in notes)


@given(focus_command())
def test_prop_focus_aliases_equivalent(pair: tuple[str, dict[str, Any]]) -> None:
    """``focus`` and ``focus-editor`` both parse to the same envelope.

    The aliases exist for ergonomics in interactive use; they must remain
    semantically identical at the parser level.
    """
    text, _ = pair
    assert text_to_json_cmd(text) == {"FocusEditor": {}}


@given(press_command())
def test_prop_press_preserves_key(pair: tuple[str, dict[str, Any]]) -> None:
    """``press <KEY>`` passes the key through verbatim under
    ``{"Press": {"key": <KEY>}}``. The parser must not lowercase or
    re-encode the key — it's a JavaFX key name.
    """
    text, expected = pair
    result = text_to_json_cmd(text)
    assert result == expected
    # Sanity: the key in the result matches the token after "press ".
    key_in_text = text.split(" ", 1)[1]
    assert result["Press"]["key"] == key_in_text


@given(type_command())
def test_prop_type_concatenates_tokens(pair: tuple[str, dict[str, Any]]) -> None:
    """``type <chars>`` produces ``{"TypeChar": {"ch": <chars>}}``.

    The ``ch`` field always exists and matches what the strategy declared
    — guarding against a regression where ``type`` starts dropping or
    re-ordering trailing tokens.
    """
    text, expected = pair
    result = text_to_json_cmd(text)
    assert result == expected
    assert "TypeChar" in result
    assert isinstance(result["TypeChar"]["ch"], str)
    assert len(result["TypeChar"]["ch"]) >= 1


@given(unknown_command_text())
def test_prop_unknown_command_raises(text: str) -> None:
    """Any text whose head is not a known command name must raise
    ``ValueError`` — never silently return a wrong-shaped dict.

    A defensive property: if a future refactor accidentally adds a
    catch-all fallback that returns ``{<head>: {}}`` for unknown heads,
    this property fires.
    """
    with pytest.raises(ValueError):
        text_to_json_cmd(text)
