import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadCatalog, Entry, Disposition } from './lib/catalog.ts';

/** docs/reports/strings-porting-backlog.md — the actionable PENDING list for the
 *  parity report. An entry is PENDING when it has a `disposition` but no
 *  `dispositionNote`. Stamping a `dispositionNote` (e.g. "ported in <sha>"
 *  or "needs UI: <one-line>") graduates the entry to DONE in the report
 *  and removes it from this backlog. */

function component(key: string): string {
  const parts = key.split('.');
  return parts.length >= 2 ? `${parts[0]}.${parts[1]}` : parts[0];
}

function dispLabel(d: Disposition): string {
  switch (d) {
    case 'port-to-web':
      return 'PORT→web';
    case 'port-to-desk':
      return 'PORT→desk';
    case 'accept':
      return 'ACCEPT';
    case 'normalize':
      return 'NORMALIZE';
  }
}

type PendingItem = {
  key: string;
  platform: string;
  value: string;
  disposition: Disposition;
};

export function generateBacklog(entries: Record<string, Entry>): string {
  const pending: PendingItem[] = [];
  for (const [key, e] of Object.entries(entries)) {
    if (!e.disposition) continue;
    if (e.dispositionNote) continue;
    pending.push({
      key,
      platform: e.platform,
      value: e.value ?? e.template ?? '',
      disposition: e.disposition,
    });
  }

  const byComp = new Map<string, PendingItem[]>();
  for (const p of pending) {
    const c = component(p.key);
    if (!byComp.has(c)) byComp.set(c, []);
    byComp.get(c)!.push(p);
  }

  const comps = Array.from(byComp.keys()).sort();
  const lines: string[] = [];
  lines.push('# UI Strings Porting Backlog');
  lines.push('');
  lines.push('> Generated by `make strings-report` (which runs both the report and the backlog).');
  lines.push('> This is the actionable list of PENDING parity work. Once an entry has a');
  lines.push('> `dispositionNote` set in `sangeet-core/src/main/resources/ui-strings.json`,');
  lines.push('> it drops off this list.');
  lines.push('');
  lines.push(`Total PENDING entries: **${pending.length}** across ${comps.length} components.`);
  lines.push('');
  lines.push('## Workflow');
  lines.push('');
  lines.push('For each PENDING entry below:');
  lines.push(
    '1. Decide if it is an **easy port** (web has an equivalent UI element — just add `title` attr',
  );
  lines.push(
    '   or merge with the parallel `.desktop` variant) or a **needs-UI** port (web is missing',
  );
  lines.push('   the element entirely; add a button/menu/dialog first).');
  lines.push('2. Land the change, then set `dispositionNote` in `ui-strings.json` — either');
  lines.push(
    '   `"ported in <commit-sha>"` for completed ports or `"needs UI: <one-line>"` to keep',
  );
  lines.push('   the entry PENDING while capturing the rationale.');
  lines.push('3. Re-run `make strings-report` to refresh both the parity report and this backlog.');
  lines.push('');
  lines.push('---');
  lines.push('');

  const counts: Record<Disposition, number> = {
    'port-to-web': 0,
    'port-to-desk': 0,
    accept: 0,
    normalize: 0,
  };
  for (const p of pending) counts[p.disposition]++;
  lines.push('## Roll-up by disposition');
  lines.push('');
  lines.push('| Disposition | Count |');
  lines.push('| ----------- | ----- |');
  for (const k of Object.keys(counts) as Disposition[]) {
    lines.push(`| ${dispLabel(k)} | ${counts[k]} |`);
  }
  lines.push('');

  lines.push('## By component');
  lines.push('');
  for (const c of comps) {
    const items = byComp.get(c)!.sort((a, b) => a.key.localeCompare(b.key));
    lines.push(`### ${c}  (${items.length} pending)`);
    lines.push('');
    lines.push('| Key | Platform | Disposition | Current value |');
    lines.push('| --- | -------- | ----------- | ------------- |');
    for (const it of items) {
      const v = it.value.length > 60 ? it.value.slice(0, 57) + '…' : it.value;
      const escaped = v.replace(/\|/g, '\\|');
      lines.push(`| \`${it.key}\` | ${it.platform} | ${dispLabel(it.disposition)} | ${escaped} |`);
    }
    lines.push('');
  }

  return lines.join('\n') + '\n';
}

// CLI entry point
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const root = resolve(process.cwd(), '..');
  const catalog = loadCatalog(resolve(root, 'sangeet-core/src/main/resources/ui-strings.json'));
  const out = generateBacklog(catalog.entries);
  writeFileSync(resolve(root, 'docs/reports/strings-porting-backlog.md'), out, 'utf-8');
  console.log('✓ Wrote docs/reports/strings-porting-backlog.md');
}
