package com.varpas.sangeet.core.strings

// GENERATED FILE — DO NOT EDIT MANUALLY.
// Source:    sangeet-core/src/main/resources/ui-strings.json
// Regenerate: sbt sangeetCore/genUiStrings   (or: make gen-strings)
//
// To add or change a string: edit ui-strings.json, then run `make gen-strings`,
// then use `UiStrings.<key>` on both desktop and web. See
// docs/developer/ui-strings-catalog.md for the full guide.

object UiStrings:

  val dialogAboutBetaNote: String = "Beta release — actively iterating toward v1.0. Expect rough edges; please file bugs via the 🐞 Report bug button in the toolbar."
  val dialogAboutBetaNoteDesktop: String = "Beta release — actively iterating toward v1.0. Expect rough edges; please file bugs via the 🐞 button in the toolbar."
  val dialogAboutClose: String = "Close"
  val dialogAboutCopyright: String = "© 2026 Bharadwaj. "
  val dialogAboutDescriptionDesktopLine1: String = "A notation editor for Hindustani classical music in the Bhatkhande style."
  val dialogAboutDescriptionDesktopLine2: String = "Designed primarily for sitar compositions — Gat, Bandish, and Palta."
  val dialogAboutDescriptionParagraph1: String = "A notation editor for Hindustani classical music in the Bhatkhande style. Built for sitar compositions: gat, bandish, palta — with mizrab strokes, meend, kan swar, gamak, and the full Bhatkhande notation set."
  val dialogAboutDescriptionParagraph2: String = "Supports Devanagari, Kannada, Telugu, and English scripts."
  val dialogAboutLicense: String = "Free and open source under the MIT License."
  val dialogAboutLicenseDesktop: String = "Free and open source. Copyright (c) 2026 Bharadwaj."
  val dialogAboutLinksDownloadDesktop: String = "Download desktop app"
  val dialogAboutLinksGithub: String = "GitHub repository"
  val dialogAboutLinksHeader: String = "Links"
  val dialogAboutLinksLicense: String = "MIT License"
  val dialogAboutLinksSelfHosting: String = "Self-hosting guide"
  val dialogAboutLinksUserGuide: String = "User guide"
  val dialogAboutLinksUserGuideDesktop: String = "User guide & documentation"
  val dialogAboutPrivacyDesktop: String = "Anonymous usage stats (which features get touched, how long sessions are — never the content you type) are sent to PostHog so I can prioritise what to build next. Set the SANGEET_ANALYTICS_DISABLED=1 environment variable to turn this off."
  val dialogAboutPrivacyHeader: String = "Privacy"
  val dialogAboutPrivacyText: String = "While you use the app, anonymous usage events (clicks, keystrokes — never the text content of fields) are sent to PostHog so I can see which features people actually reach for. If you click \"🐞 Report bug\", the last few minutes of your activity in this page are recorded as a video-like replay and sent along with your message so I can reproduce what you saw. Password fields are never captured. Nothing leaves your browser unless you click Send. Reports auto-delete from storage after 90 days. The desktop app sends a smaller, separate set of anonymous events to a different PostHog project for the same reason; users can opt out by setting SANGEET_ANALYTICS_DISABLED=1."
  val dialogAboutSampleToggle: String = "Show sample composition on startup"
  val dialogAboutSupportLink: String = "Support the project"
  val dialogAboutSupportSuffix: String = " — UPI / PayPal options."
  val dialogAboutSupportText: String = "💖 "
  val dialogAboutTech: String = "Desktop: Scala 3 + ScalaFX. Web: Elm + Tapir."
  val dialogAboutTechDesktop: String = "Built with Scala 3 + ScalaFX (desktop) and Elm + Tapir (web)"
  val dialogAboutTitle: String = "Sangeet Notes Editor"
  val toolbarBetaBadge: String = "BETA"
  val toolbarBetaTooltip: String = "Beta software — actively iterating toward v1.0. Use 🐞 Report bug for issues."
  val toolbarEditRedo: String = "Redo"
  val toolbarEditRedoTooltip: String = "Redo (Ctrl+Y)"
  val toolbarEditRedoTooltipDesktop: String = "Redo (Ctrl+Shift+Z)"
  val toolbarEditUndo: String = "Undo"
  val toolbarEditUndoTooltip: String = "Undo (Ctrl+Z)"
  val toolbarEditUndoTooltipDesktop: String = "Undo last edit (Ctrl+Z)"
  val toolbarFileCopyTooltip: String = "Copy (Ctrl+C)"
  val toolbarFileCopyTooltipDesktop: String = "Copy selected events (Ctrl+C)"
  val toolbarFileCutTooltip: String = "Cut (Ctrl+X)"
  val toolbarFileCutTooltipDesktop: String = "Cut selected events (Ctrl+X)"
  val toolbarFileExportHtml: String = "HTML"
  val toolbarFileExportHtmlTooltip: String = "Export HTML"
  val toolbarFileExportHtmlTooltipDesktop: String = "Export composition as HTML"
  val toolbarFileNew: String = "New"
  val toolbarFileNewTooltip: String = "New Composition (Ctrl+N)"
  val toolbarFileNewTooltipDesktop: String = "Create a new composition"
  val toolbarFileOpen: String = "Open"
  val toolbarFileOpenTooltip: String = "Open File"
  val toolbarFileOpenTooltipDesktop: String = "Open a .swar file"
  val toolbarFileOpenFolderTooltip: String = "Open a folder in the file browser"
  val toolbarFilePasteTooltip: String = "Paste (Ctrl+V)"
  val toolbarFilePasteTooltipDesktop: String = "Paste clipboard events (Ctrl+V)"
  val toolbarFileSave: String = "Save"
  val toolbarFileSaveTooltip: String = "Save File (Ctrl+S)"
  val toolbarFileSaveTooltipDesktop: String = "Save composition to current file"
  val toolbarFileSaveAsTooltip: String = "Save composition as a new .swar file"
  val toolbarHelpAbout: String = "About"
  val toolbarHelpAboutTooltip: String = "About"
  val toolbarHelpAboutTooltipDesktop: String = "About Sangeet Notes Editor"
  val toolbarHelpKeyboardShortcuts: String = "?"
  val toolbarHelpKeyboardShortcutsTooltip: String = "Keyboard shortcuts (?)"
  val toolbarHelpKeyboardShortcutsTooltipDesktop: String = "Show keyboard shortcuts (?)"
  val toolbarHelpProperties: String = "Properties"
  val toolbarHelpPropertiesTooltip: String = "Composition Properties"
  val toolbarHelpPropertiesTooltipDesktop: String = "Edit composition metadata"
  val toolbarHelpReportBug: String = "🐞 Report bug"
  val toolbarHelpReportBugTooltip: String = "Report a bug — includes a short replay so it can be reproduced"
  val toolbarHelpReportBugTooltipDesktop: String = "Report a bug — includes a screenshot + recent keystrokes + the open composition"
  val toolbarHelpSupport: String = "💖"
  val toolbarHelpSupportTooltip: String = "Support the project — donate via UPI or PayPal"
  val toolbarHelpSupportTooltipDesktop: String = "Support the project"
  val toolbarHelpUserGuideTooltip: String = "Open the user guide (F1)"
  val toolbarModeStroke: String = "Mode: Stroke"
  val toolbarModeSwar: String = "Mode: Swar"
  val toolbarOrnamentKrintanEnd: String = "Krintan: type end note / Enter"
  val toolbarOrnamentKrintanStart: String = "Krintan: type start note"
  val toolbarOrnamentMeendEnd: String = "Meend: type end note"
  val toolbarOrnamentMeendStart: String = "Meend: type start note"
  val toolbarScriptDevanagari: String = "Devanagari"
  val toolbarScriptDevanagariDesktop: String = "Devanagari (Hindi)"
  val toolbarScriptEnglish: String = "English"
  val toolbarScriptKannada: String = "Kannada"
  val toolbarScriptLabel: String = "Script:"
  val toolbarScriptTelugu: String = "Telugu"
  val toolbarScriptTooltip: String = "Change notation script"
  val toolbarSectionAddTooltip: String = "Add Section"
  val toolbarSectionAddTooltipDesktop: String = "Add a new section to the composition"
  val toolbarSectionMoveDownTooltip: String = "Move section down"
  val toolbarSectionMoveUpTooltip: String = "Move section up"
  val toolbarSectionRemoveTooltip: String = "Remove current section"
  val toolbarSectionRemoveTooltipDesktop: String = "Remove the current section"
  val toolbarSectionRenameTooltip: String = "Rename current section"
  val toolbarSectionRenameTooltipDesktop: String = "Rename the current section (F2)"
  val toolbarTabsCloseTooltip: String = "Close tab"
  val toolbarTabsNewTooltip: String = "New Tab"
  val toolbarThemeToggleTooltip: String = "Toggle light / dark theme"
  val toolbarViewToggleKeyboardLegend: String = "Keys"
  val toolbarViewToggleKeyboardLegendTooltip: String = "Keyboard Shortcuts"
  val toolbarViewToggleSahityaLine: String = "Sahitya"
  val toolbarViewToggleSahityaLineTooltip: String = "Toggle Sahitya Line"
  val toolbarViewToggleStrokeLine: String = "Strokes"
  val toolbarViewToggleStrokeLineTooltip: String = "Toggle Stroke Line"

  def dialogAboutLinksWebVersion(url: String): String = s"Web version: $url"
  def dialogAboutVersion(version: String): String = s"Version $version"
  def toolbarOrnamentMurki(count: Int): String = s"Murki: $count notes (Enter to apply)"
  def toolbarOrnamentSingleNote(name: String): String = s"Orn: $name (type note)"
  def toolbarOrnamentZamzama(count: Int): String = s"Zamzama: $count notes (Enter to apply)"
